<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Fundraiser;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * FundraiserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FundraiserRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Fundraiser::class);
    }

    public function getFundraisersByAverageRating(string $orderBy): array
    {
        $em = $this->getEntityManager();

        $queryString = '
            SELECT Fundraiser.id, Fundraiser.name, Fundraiser.description, Fundraiser.thumbnail, Fundraiser.createdDate,AVG(Review.rating) as avg_rating
            FROM AppBundle:Fundraiser Fundraiser
            LEFT JOIN AppBundle:Review Review
            WHERE Fundraiser.id = Review.fundraiser
            GROUP BY Fundraiser.id ORDER BY';

        $queryString .= ($orderBy === "avg_rating") ? " avg_rating DESC" : " Fundraiser.name ASC";

        $query = $em->createQuery($queryString);
        $result = $query->getResult();

        return $result;
    }
}
