<?php

namespace AppBundle\Repository;

/**
 * FundraiserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FundraiserRepository extends \Doctrine\ORM\EntityRepository
{
}
