<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Author;
use AppBundle\Entity\Fundraiser;
use AppBundle\Entity\Review;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Review::class);
    }

    public function getReviewByUserIdAndFundraiserId(Author $author, Fundraiser $fundraiser): ?Review
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery('
            SELECT Review
            FROM AppBundle:Review Review
            WHERE Review.author = :authorId
            AND Review.fundraiser = :fundraiserId
        ');

        $query->setParameter(":authorId", $author->getId());
        $query->setParameter(":fundraiserId", $fundraiser->getId());
        $query->setMaxResults(1);

        $existingReviews = $query->getResult();

        return (count($existingReviews) > 0) ? $existingReviews[0] : null;
    }
}
